//! manager.exe patcher (Y2K fix, season-start-year) for Apertura 98/99.
//! Owned by Agent C (PLAN.md §6 "Agent C — Manager patcher").
//!
//! ## Status
//! - [`patch_y2k`], [`verify`]/[`verify_bytes`], backup + [`restore_from_backup`]:
//!   implemented, TDD'd against a synthetic fixture (see
//!   `fixtures/manager_synthetic/`, generated by this crate's tests — no real
//!   Apertura `manager.exe` has been supplied yet).
//! - [`set_start_year`]: **deferred**. The season-start-year (and
//!   calendar/competition) byte offsets are edition-specific and have not
//!   been confirmed against a real Apertura 98/99 `manager.exe` (~2397 KB) —
//!   see PLAN.md risk #4. Calling it returns a typed [`PcfError`] instead of
//!   guessing an offset and silently corrupting the binary.
//!
//! TODO(C): confirm season-start-year offset and calendar/competition
//! offsets against a real Apertura manager.exe (~2397KB) once user supplies one.

use pcf_model::{ManagerPatch, PatchReport, PcfError};
use std::fs;
use std::path::{Path, PathBuf};

/// Bytes searched for by the Y2K fix (pre-patch state). Given by PLAN.md
/// Appendix B — safe to hardcode as the search pattern.
pub const Y2K_PATTERN_BEFORE: [u8; 12] = [
    0x6C, 0x07, 0x00, 0x00, 0x76, 0x08, 0x81, 0xFD, 0xD0, 0x07, 0x00, 0x00,
];

/// Bytes written by the Y2K fix (post-patch state).
pub const Y2K_PATTERN_AFTER: [u8; 12] = [
    0x01, 0x00, 0x00, 0x00, 0x76, 0x08, 0x81, 0xFD, 0xFF, 0xFF, 0x00, 0x00,
];

/// Documented Apertura 98/99 `manager.exe` size (PLAN.md Appendix B).
pub const EXPECTED_SIZE_BYTES: u64 = 2397 * 1024;

/// Real installs may differ by a few KB (padding, minor build variance); the
/// exact tolerance is unconfirmed pending a real fixture (PLAN.md risk #4).
/// Kept generous-but-bounded so an unrelated file (e.g. a multi-MB installer
/// or a tiny text file) is rejected as "not an Apertura manager" rather than
/// silently patched.
pub const SIZE_TOLERANCE_BYTES: u64 = 200 * 1024;

/// Result of scanning a manager.exe candidate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PatchState {
    /// Right size window, contains the pre-patch Y2K signature.
    Unpatched,
    /// Right size window, contains the post-patch Y2K signature.
    AlreadyPatched,
    /// Wrong size and/or neither signature found — refuse to touch it.
    NotApertura,
}

fn is_apertura_sized(len: u64) -> bool {
    let lower = EXPECTED_SIZE_BYTES.saturating_sub(SIZE_TOLERANCE_BYTES);
    let upper = EXPECTED_SIZE_BYTES + SIZE_TOLERANCE_BYTES;
    (lower..=upper).contains(&len)
}

fn find_pattern(haystack: &[u8], pattern: &[u8]) -> Option<usize> {
    if pattern.is_empty() || haystack.len() < pattern.len() {
        return None;
    }
    haystack.windows(pattern.len()).position(|w| w == pattern)
}

/// Pure, in-memory verification: a size/signature guard that keeps
/// [`patch_y2k`] from ever mispatching a non-Apertura binary
/// (PLAN.md risk #4 / Agent C acceptance criteria).
pub fn verify_bytes(bytes: &[u8]) -> PatchState {
    if !is_apertura_sized(bytes.len() as u64) {
        return PatchState::NotApertura;
    }
    if find_pattern(bytes, &Y2K_PATTERN_AFTER).is_some() {
        PatchState::AlreadyPatched
    } else if find_pattern(bytes, &Y2K_PATTERN_BEFORE).is_some() {
        PatchState::Unpatched
    } else {
        // Right size, but neither the pre- nor post-patch signature is
        // present: don't guess, treat as unrecognized.
        PatchState::NotApertura
    }
}

fn io_error(code: &str, path: &Path, err: &std::io::Error) -> PcfError {
    PcfError::new(code, format!("I/O error on {}: {err}", path.display()))
        .with_context(path.display().to_string())
}

fn not_apertura_error(path: &Path, size: usize) -> PcfError {
    PcfError::new(
        "manager/not-apertura",
        format!(
            "{} does not look like an Apertura 98/99 manager.exe (expected ~{} KB with a known Y2K signature, got {} bytes) — refusing to patch to avoid corrupting an unrelated binary",
            path.display(),
            EXPECTED_SIZE_BYTES / 1024,
            size
        ),
    )
    .with_context(path.display().to_string())
}

/// Reads `path` and runs [`verify_bytes`] against its contents.
pub fn verify(path: &Path) -> Result<PatchState, PcfError> {
    let bytes = fs::read(path).map_err(|e| io_error("manager/read", path, &e))?;
    Ok(verify_bytes(&bytes))
}

/// The `<manager.exe>.bak` sibling path used for backups.
pub fn backup_path_for(path: &Path) -> PathBuf {
    let mut name = path
        .file_name()
        .map(|n| n.to_os_string())
        .unwrap_or_default();
    name.push(".bak");
    path.with_file_name(name)
}

/// Writes a `.bak` backup of `original_bytes` next to `path`, without
/// overwriting an existing backup — so the *first* backup, taken before any
/// patch has ever been applied, is preserved even if a patch function is
/// called more than once (idempotency guard).
fn ensure_backup(path: &Path, original_bytes: &[u8]) -> Result<PathBuf, PcfError> {
    let backup = backup_path_for(path);
    if !backup.exists() {
        fs::write(&backup, original_bytes).map_err(|e| io_error("manager/backup", &backup, &e))?;
    }
    Ok(backup)
}

/// Restores `path` from the `.bak` backup written by [`patch_y2k`].
pub fn restore_from_backup(path: &Path) -> Result<(), PcfError> {
    let backup = backup_path_for(path);
    let bytes = fs::read(&backup).map_err(|e| io_error("manager/restore", &backup, &e))?;
    fs::write(path, bytes).map_err(|e| io_error("manager/restore", path, &e))?;
    Ok(())
}

/// Applies the Y2K fix in place, replacing
/// `6C070000760881FDD0070000` with `01000000760881FDFFFF0000`
/// (PLAN.md Appendix B). Always backs up first. Idempotent: calling this on
/// an already-patched file is a verified no-op (reported via
/// `PatchReport.already_patched`), not a silent double-write.
pub fn patch_y2k(path: &Path) -> Result<PatchReport, PcfError> {
    let bytes = fs::read(path).map_err(|e| io_error("manager/read", path, &e))?;

    match verify_bytes(&bytes) {
        PatchState::NotApertura => Err(not_apertura_error(path, bytes.len())),
        PatchState::AlreadyPatched => Ok(PatchReport {
            already_patched: true,
            backup_path: backup_path_for(path).display().to_string(),
            applied: Vec::new(),
        }),
        PatchState::Unpatched => {
            let backup = ensure_backup(path, &bytes)?;
            let offset = match find_pattern(&bytes, &Y2K_PATTERN_BEFORE) {
                Some(offset) => offset,
                None => {
                    return Err(PcfError::new(
                        "manager/pattern-not-found",
                        "internal consistency error: verify_bytes reported Unpatched but the pre-patch pattern could not be located",
                    )
                    .with_context(path.display().to_string()));
                }
            };
            let mut patched = bytes;
            patched[offset..offset + Y2K_PATTERN_AFTER.len()].copy_from_slice(&Y2K_PATTERN_AFTER);
            fs::write(path, &patched).map_err(|e| io_error("manager/write", path, &e))?;
            Ok(PatchReport {
                already_patched: false,
                backup_path: backup.display().to_string(),
                applied: vec!["y2k".to_string()],
            })
        }
    }
}

/// Season-start-year patch. **Deferred** (PLAN.md risk #4): the byte offset
/// is edition-specific and has not been confirmed against a real Apertura
/// 98/99 `manager.exe`. Returns a typed error instead of guessing an offset.
///
/// TODO(C): confirm season-start-year offset and calendar/competition
/// offsets against a real Apertura manager.exe (~2397KB) once user supplies one.
pub fn set_start_year(path: &Path, _year: u16) -> Result<PatchReport, PcfError> {
    Err(PcfError::new(
        "manager/start-year-unconfirmed",
        "the season-start-year offset is not yet confirmed for this Apertura 98/99 edition (PLAN.md risk #4); supply a real manager.exe (~2397 KB) so the offset can be confirmed before this is enabled",
    )
    .with_context(path.display().to_string()))
}

/// Orchestrates a `patch_manager(path, opts)` request (PLAN.md §4.3 IPC
/// command shape) on top of the primitives above. `start_year` is checked
/// first and fails fast (without touching the file) so a request combining
/// a confirmed fix with an unconfirmed one never partially applies.
pub fn patch(path: &Path, opts: &ManagerPatch) -> Result<PatchReport, PcfError> {
    if let Some(year) = opts.start_year {
        return set_start_year(path, year);
    }
    if opts.y2k {
        return patch_y2k(path);
    }
    let already_patched = verify(path)? == PatchState::AlreadyPatched;
    Ok(PatchReport {
        already_patched,
        backup_path: backup_path_for(path).display().to_string(),
        applied: Vec::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A plain-text banner so anyone who opens the fixture in a hex editor
    /// immediately sees it isn't a real executable.
    const SYNTHETIC_HEADER: &[u8] =
        b"PCF-MANAGER-SYNTHETIC-PLACEHOLDER -- NOT A REAL EXECUTABLE -- \
generated by crates/pcf-manager tests for TDD only, see fixtures/manager_synthetic/README.txt\n";

    const PATTERN_OFFSET: usize = 4096;

    fn build_synthetic_manager_bytes(pattern: &[u8]) -> Vec<u8> {
        // Filler byte chosen arbitrarily (0xAA); size matches the documented
        // ~2397 KB Apertura manager.exe exactly so it sits inside the guard.
        let mut bytes = vec![0xAAu8; EXPECTED_SIZE_BYTES as usize];
        bytes[..SYNTHETIC_HEADER.len()].copy_from_slice(SYNTHETIC_HEADER);
        bytes[PATTERN_OFFSET..PATTERN_OFFSET + pattern.len()].copy_from_slice(pattern);
        bytes
    }

    fn fixture_path() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/manager_synthetic/PLACEHOLDER_manager_98_99.bin")
    }

    fn temp_manager_path(name: &str) -> PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!(
            "pcf_manager_test_{name}_{}.exe",
            std::process::id()
        ));
        p
    }

    /// RAII helper: writes a manager.exe-shaped fixture to a private temp
    /// path and removes it (plus any `.bak`) when the test ends, so mutation
    /// tests never touch the checked-in synthetic fixture.
    struct TempManagerFile {
        path: PathBuf,
    }

    impl TempManagerFile {
        fn new(name: &str, bytes: &[u8]) -> Self {
            let path = temp_manager_path(name);
            fs::write(&path, bytes).expect("write temp manager fixture");
            Self { path }
        }
    }

    impl Drop for TempManagerFile {
        fn drop(&mut self) {
            let _ = fs::remove_file(&self.path);
            let _ = fs::remove_file(backup_path_for(&self.path));
        }
    }

    // ---------------------------------------------------------------
    // Fixture materialization: hand-constructed synthetic binary, saved
    // under fixtures/manager_synthetic/ (not fixtures/golden|charmap|pointers)
    // since no real Apertura manager.exe has been supplied yet.
    // ---------------------------------------------------------------

    #[test]
    fn synthetic_fixture_is_materialized_on_disk_and_reads_as_unpatched() {
        let path = fixture_path();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create fixtures/manager_synthetic dir");
        }
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        fs::write(&path, &bytes).expect("write synthetic fixture");

        let read_back = fs::read(&path).expect("read synthetic fixture back");
        assert_eq!(read_back, bytes);
        assert_eq!(read_back.len() as u64, EXPECTED_SIZE_BYTES);
        assert_eq!(verify_bytes(&read_back), PatchState::Unpatched);
    }

    // ---------------------------------------------------------------
    // Red-green step 1: pattern found and replaced correctly.
    // ---------------------------------------------------------------

    #[test]
    fn patch_y2k_replaces_pattern_and_reports_applied() {
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        let temp = TempManagerFile::new("replace", &bytes);

        let report = patch_y2k(&temp.path).expect("patch_y2k should succeed");

        assert!(!report.already_patched);
        assert_eq!(report.applied, vec!["y2k".to_string()]);

        let patched_bytes = fs::read(&temp.path).expect("read patched file");
        assert_eq!(
            &patched_bytes[PATTERN_OFFSET..PATTERN_OFFSET + Y2K_PATTERN_AFTER.len()],
            &Y2K_PATTERN_AFTER
        );
        assert_eq!(verify_bytes(&patched_bytes), PatchState::AlreadyPatched);
    }

    // ---------------------------------------------------------------
    // Red-green step 2: backup file created with pre-patch bytes.
    // ---------------------------------------------------------------

    #[test]
    fn patch_y2k_creates_backup_with_original_bytes() {
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        let temp = TempManagerFile::new("backup", &bytes);

        let report = patch_y2k(&temp.path).expect("patch_y2k should succeed");

        let backup_path = backup_path_for(&temp.path);
        assert_eq!(report.backup_path, backup_path.display().to_string());
        let backup_bytes = fs::read(&backup_path).expect("read backup file");
        assert_eq!(backup_bytes, bytes, "backup must hold the pre-patch bytes");
    }

    #[test]
    fn restore_from_backup_puts_original_bytes_back() {
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        let temp = TempManagerFile::new("restore", &bytes);

        patch_y2k(&temp.path).expect("patch_y2k should succeed");
        assert_ne!(fs::read(&temp.path).expect("read patched"), bytes);

        restore_from_backup(&temp.path).expect("restore should succeed");
        assert_eq!(fs::read(&temp.path).expect("read restored"), bytes);
    }

    // ---------------------------------------------------------------
    // Red-green step 3: idempotency — second patch call is a no-op,
    // verify() reports already-patched, no silent double-write.
    // ---------------------------------------------------------------

    #[test]
    fn patch_y2k_is_idempotent() {
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        let temp = TempManagerFile::new("idempotent", &bytes);

        let first = patch_y2k(&temp.path).expect("first patch should succeed");
        assert!(!first.already_patched);
        let once_patched_bytes = fs::read(&temp.path).expect("read once-patched");

        let second = patch_y2k(&temp.path).expect("second patch should succeed");
        assert!(
            second.already_patched,
            "second call must report already-patched"
        );
        assert!(
            second.applied.is_empty(),
            "second call must not re-apply anything"
        );

        let twice_patched_bytes = fs::read(&temp.path).expect("read twice-patched");
        assert_eq!(
            once_patched_bytes, twice_patched_bytes,
            "idempotent patch must not change the file on the second call"
        );
        assert_eq!(
            verify(&temp.path).expect("verify"),
            PatchState::AlreadyPatched
        );
    }

    // ---------------------------------------------------------------
    // Red-green step 4: size/signature guard rejects non-Apertura binaries.
    // ---------------------------------------------------------------

    #[test]
    fn verify_rejects_binary_that_is_the_wrong_size() {
        let mut bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        bytes.truncate(1024); // a 1 KB file is nowhere near ~2397 KB
        assert_eq!(verify_bytes(&bytes), PatchState::NotApertura);
    }

    #[test]
    fn verify_rejects_right_size_binary_without_known_signature() {
        // Right size, but no Y2K signature anywhere: not a recognized
        // Apertura manager.exe, even though the size guard alone would pass.
        let bytes = vec![0x00u8; EXPECTED_SIZE_BYTES as usize];
        assert_eq!(verify_bytes(&bytes), PatchState::NotApertura);
    }

    #[test]
    fn patch_y2k_refuses_to_touch_a_non_apertura_binary() {
        let bytes = vec![0x00u8; 4096]; // far too small, no signature
        let temp = TempManagerFile::new("guard", &bytes);

        let err = patch_y2k(&temp.path).expect_err("must refuse to patch");
        assert_eq!(err.code, "manager/not-apertura");

        // Guard must be a true no-op: no backup, no mutation.
        assert!(!backup_path_for(&temp.path).exists());
        assert_eq!(fs::read(&temp.path).expect("read untouched file"), bytes);
    }

    // ---------------------------------------------------------------
    // Red-green step 5: set_start_year returns the "not confirmed" typed
    // error instead of guessing an offset and corrupting bytes.
    // ---------------------------------------------------------------

    #[test]
    fn set_start_year_returns_not_confirmed_error_and_leaves_bytes_untouched() {
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        let temp = TempManagerFile::new("start_year", &bytes);

        let err = set_start_year(&temp.path, 1999).expect_err("must be unconfirmed");
        assert_eq!(err.code, "manager/start-year-unconfirmed");

        assert_eq!(fs::read(&temp.path).expect("read untouched file"), bytes);
        assert!(
            !backup_path_for(&temp.path).exists(),
            "must not even take a backup"
        );
    }

    #[test]
    fn patch_orchestrator_fails_fast_on_start_year_without_touching_file() {
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        let temp = TempManagerFile::new("orchestrator_start_year", &bytes);

        let opts = ManagerPatch {
            y2k: true,
            start_year: Some(1999),
        };
        let err = patch(&temp.path, &opts).expect_err("start_year must fail fast");
        assert_eq!(err.code, "manager/start-year-unconfirmed");

        // Because start_year is checked first, the y2k fix must NOT have
        // been silently applied alongside the rejected start_year request.
        assert_eq!(fs::read(&temp.path).expect("read untouched file"), bytes);
    }

    #[test]
    fn patch_orchestrator_applies_y2k_when_only_y2k_is_requested() {
        let bytes = build_synthetic_manager_bytes(&Y2K_PATTERN_BEFORE);
        let temp = TempManagerFile::new("orchestrator_y2k", &bytes);

        let opts = ManagerPatch {
            y2k: true,
            start_year: None,
        };
        let report = patch(&temp.path, &opts).expect("y2k-only patch should succeed");
        assert!(!report.already_patched);
        assert_eq!(report.applied, vec!["y2k".to_string()]);
    }
}
